name: Jira Webhook
description: Call a jira webhook
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issues:
    description: Key of the issues to be passed
    required: true
  webhook:
    description: The transition to apply to the issue, e.g. 'In Progress'
    required: true
  eventData:
    description: select additional info from ?
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'
